### ISSUE TITLE
Fix deployment order on UI

### ISSUE THREAD

**Issue by iffyuva** [code-mancers/dockup#106]
![image](https://cloud.githubusercontent.com/assets/1108398/19099783/326eddc8-8ad7-11e6-9232-18b20ef60b2d.png)

its very confusing when order is jumbled like this. I have hunt through numbers on first column to look at latest deploy

Thanks.

**Comment by emilsoman** [comment]
This is a known issue. I have a plan to move deployment list to a different page and show only the currently deployed project below the form. Until then I'll keep this open.
