### ISSUE TITLE
Enable autocomplete for org name and repo name

### ISSUE THREAD

**Issue by iffyuva** [code-mancers/dockup#107]
![image](https://cloud.githubusercontent.com/assets/1108398/19099889/0c3d122c-8ad8-11e6-8b6d-5455242d29d0.png)

Auto completion exists for branch name. Its easy to deploy already deployed branch again. It would be better if auto completion is enabled for org name and repo name so that i don't have to type `code-mancers` again and again.

**Comment by emilsoman** [comment]
@iffyuva you mean browser's autosuggest right?

**Comment by iffyuva** [comment]
@emilsoman yes

**Comment by emilsoman** [comment]
I remember reading an issue regarding browsers not auto suggesting input fields which are managed by React. If that's solved, this should be fixed.

**Comment by emilsoman** [comment]
Once we move URL whitelisting feature over to DockupUI app, we can just show a typeahead dropdown of whitelisted git URLs.

**Comment by emilsoman** [comment]
Closed by #118
