### ISSUE TITLE
Why is status `started` when deployment has completed

### ISSUE THREAD

**Issue by iffyuva** [code-mancers/dockup#108]
Deployment status starts from `starting`, and reaches `started`. Can you be more specific with these states. Should I read these states are `deployment starting` and `deployment started`, or `App starting` and `App started` ? Its confusing from the UI

**Comment by emilsoman** [comment]
You know deployment has started once you go from "queued" to "cloning repo" status right? That means when I see "starting" -> "checking urls" -> "started" I know it's the app that's started.

**Comment by emilsoman** [comment]
Closed by #110
