### ISSUE TITLE
Bug - Failed deployment count as deployment and cant be deleted

### ISSUE THREAD

**Issue by rafeequl** [code-mancers/dockup#182]
Step to reproduce : 

- Deploy invalid/non-exist branch name
- Dockup delpoyment will fail
- Tries to delete
- Repeat untill reach the number of max deployment
- Delete deployment => failed
- Deploy another branch => will be forever queued

Expected behaviour : 
- For every failed deployment, we should be able to delete it manually
- We might not want to delete it automatically since logs is often usefull for investigation

**Comment by iffyuva** [comment]
This is fixed for helm backend https://github.com/code-mancers/dockup/pull/181 https://github.com/code-mancers/dockup/pull/181/commits/a66f20d669dd5161d29b9b45f02287752aba9706

Regarding logs, they are preserved in stackdriver. So we don't have to worry.
