### ISSUE TITLE
Feature UI to manage max deployment and concurrent build

### ISSUE THREAD

**Issue by rafeequl** [code-mancers/dockup#183]
It would be nice if as an admin we can do the following stuff from the ui : 

- Set the number of max deployment
- Set the number of max concurent build

**Comment by iffyuva** [comment]
Do we need any restrictions anymore since we've moved to k8s? /cc @emilsoman

**Comment by emilsoman** [comment]
@iffyuva do we limit scaling in k8s by setting a max number of nodes to which the cluster can expand? If we have that, it is possible to deplete resources if deployment requests keep piling up - or does k8s have the intelligence to queue deployments?

**Comment by iffyuva** [comment]
@emilsoman yeah, we set max no of nodes, and if there are more and more deploys, all 5 nodes will be used up. Further deploys will all be in "Pending" state.

**Comment by emilsoman** [comment]
Closing this because we removed the Elixir deployment queue in favor of k8s deployment scheduling.
