### ISSUE TITLE
When server restarts, dockup doesn't resume polling

### ISSUE THREAD

**Issue by iffyuva** [code-mancers/dockup#186]
Steps to reproduce:

- Deploy a project, dockup starts polling the url
- Restart the dockup server

Dockup server doesn't resume polling. How to fix this issue?

**Comment by emilsoman** [comment]
How to fix this - polling should be done in a supervised process that reads deployments from the DB when it starts and do polling based on the current state of deployments.

**Comment by iffyuva** [comment]
Yes, makes sense. Or when we have message bus, we can just current state of deployments, and polling happens automatically.

**Comment by iffyuva** [comment]
Man this is high priority. Today k8s cluster auto-scaled to 5 nodes, dockup pod got rescheduled. All deploys are stuck with "Starting" status.

**Comment by emilsoman** [comment]
I am starting on this issue then.
