### ISSUE TITLE
Hibernating should clear the "urls" and "log_url" fields of deployments

### ISSUE THREAD

**Issue by emilsoman** [code-mancers/dockup#193]
Also, do we need a "hibernated_at" field now? /cc @iffyuva

**Comment by iffyuva** [comment]
Why should we clear it btw? Regarding `hibernated_at`, im thinking if we should have audit trail for state changes.

**Comment by emilsoman** [comment]
These should be cleared so that we dont have to do state checks in the UI when rendering "open" or "logs" button in the UI. Currently hibernated, hibernating and waking up states are manually checked to hide those buttons. Also it makes sense to not keep stale log urls or app urls since we reset it again when waking up deployments.

**Comment by iffyuva** [comment]
@emilsoman is it done as part of PR #204 ?
