### ISSUE TITLE
Bug: Deleted deployments have to be ignored

### ISSUE THREAD

**Issue by iffyuva** [code-mancers/dockup#199]
Code: https://github.com/code-mancers/dockup/blob/84831d82dd5/apps/dockup_ui/lib/dockup_ui/deployment_queue.ex#L127

Right now we have 30 deleted deployments. This code is preventing further deploys. Let me know if more details are required.

**Comment by emilsoman** [comment]
I was not able to reproduce issue with deleted deployments holding up the queue, but I found an issue which causes current_deployment_count to be more than max_deployment_count. I have fixed that in #201
