### ISSUE TITLE
Create new deployment form

### ISSUE THREAD

**Issue by emilsoman** [code-mancers/dockup#221]
Current form:

![image](https://user-images.githubusercontent.com/1707078/43370576-f4e94718-939e-11e8-8601-f9eff7c9e51f.png)

Markup:

```javascript
        <form>
          <div className="form-group">
            <label>Git URL</label>
            <GitUrlInput urls={this.urls} onUrlChange={this.handleUrlChange}/>
          </div>
          <div className="form-group">
            <label htmlFor="branch">Branch</label>
            <input className="form-control" id="branch" onChange={(event) => { this.handleBranchChange(event.target.value)}}/>
          </div>

          <button type="submit" onClick={this.handleDeployClick} disabled={!this.validInputs()} className="btn btn-primary">Deploy</button>
        </form>

```

Requirements:

Given the following props, change the above UI to look like this:

```
containerSpecs: [
  {id: 1, image: "my_frontend", defaultTag: "latest"},
  {id: 2, image: "my-backend", defaultTag: "master"}
]
```

Render a UI that looks like this:

![image](https://user-images.githubusercontent.com/1707078/43370622-ed4a3246-939f-11e8-94e1-4f0d78f7d325.png)

Also change the payload sent in the ajax request to:

```javascript
[
  {id: 1, image: "nginx", tag: "edited_default_tag"},
  ...
]

```

**Comment by arshadkazmi42** [comment]
I am interested to take this.

Getting this error during setup. Can someone help me with the setup?

` GenServer #PID<0.280.0> terminating
** (KeyError) key :password not found in: [types: Postgrex.DefaultTypes, username: "root", backoff_type: :stop, pool: DBConnection.Connection, database: "postgres", otp_app: :dockup_ui, repo: DockupUi.Repo, timeout: 15000, pool_timeout: 5000, adapter: Ecto.Adapters.Postgres, hostname: "localhost", pool_size: 10, extensions: [{Postgrex.Extensions.JSON, [library: Poison]}]]
    (elixir) lib/keyword.ex:386: Keyword.fetch!/2
    (postgrex) lib/postgrex/protocol.ex:581: Postgrex.Protocol.auth_md5/4
    (postgrex) lib/postgrex/protocol.ex:475: Postgrex.Protocol.handshake/2
    (db_connection) lib/db_connection/connection.ex:134: DBConnection.Connection.connect/2
    (connection) lib/connection.ex:622: Connection.enter_connect/5
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
Last message: nil
State: Postgrex.Protocol`

**Comment by emilsoman** [comment]
@arshadkazmi42 thanks for offering to help. But I think @HarshwardhanSingh has already picked this up. Regarding the error you're seeing, it looks like something from the DB connection. It should work if you have a default postgres installation locally.

**Comment by emilsoman** [comment]
Fixed in k8s-ui branch

**Comment by arshadkazmi42** [comment]
@emilsoman  Thank you for the info. And also thanks for the setup feedback. I have a postgres running locally. I think it has different login. I will try creating a new postgres
