### ISSUE TITLE
Use papertrail for logging

### ISSUE THREAD

**Issue by emilsoman** [code-mancers/dockup#24]
* Use search query to group logs per project
* Let papertrail take care of authentication
* Use https://github.com/larskrantz/logger_papertrail_backend

**Comment by kgrz** [comment]
This will mandate Heroku isn't it?

**Comment by emilsoman** [comment]
Nope, we can use papertrail as an individual service :
https://papertrailapp.com

**Comment by kgrz** [comment]
But still it looks like a cloud logging service, any reason why standalone logging systems are not considered? If I use dockup, why should I pay money to papertrail?

**Comment by emilsoman** [comment]
@kgrz no need to pay papertrail. You can use the free service if you want to see logs. The reason for using papertrail:

1. Currently the logs can be accessed by anyone. Since deployments can log confidential things to the console, we should have some authentication. Instead of building a logging service with authentication, we might as well ask the user to use a logging service (papertrail free account as the sane default)
2. Papertrail can filter logs using a query param to the URL. That means to filter logs for a project "foo", I can generate a papertrail URL similar to : "<papertrail_log_url>?q=foo" . This makes reading log tails easier when there are concurrent logs.
3. Our existing way of tailing logs requires a node package called "frontail" which means we need nodejs as a prerequisite just for showing logs on the browser.
4. The other alternative is to implement our own Elixir logging backend which will start a server and ship log messages over a websocket to the browser. I initially wanted to do this, but it will delay the release of dockup. It will be a nice open source elixir project to create and we can do it once the initial version is ready and possibly use that as the default logging technique.

**Comment by emilsoman** [comment]
I gave this some more thought and now I feel we should roll our own logging. Even though using papertrail for logging would be the fastest way to ship this feature, it's not the best way since we are adding another service into the picture.

Here's my proposed solution:
1. Change system command API to emit streaming stdout.
2. Create a logger service that can push logs to a phoenix channel.
3. Docker logs can be captured using the attach API : https://docs.docker.com/engine/reference/api/docker_remote_api_v1.19/#attach-to-a-container-websocket
4. Expose them in the UI using websocket (using phoenix channels)
