### ISSUE TITLE
Specify CWD in each system command

### ISSUE THREAD

**Issue by emilsoman** [code-mancers/dockup#45]
Since CWD is per OS process, changing it in an erlang process and then executing commands will cause problems when multiple processes run concurrently.

`System.cmd` supports a `cd:` option which we can use to avoid this problem. [Link to question in elixir talk mailing list](https://groups.google.com/forum/#!topic/elixir-lang-talk/mv9wlbkl1lc).

**Comment by emilsoman** [comment]
@iffyuva Actually, I fixed this in most places in PR #59 ( [Relevant code](https://github.com/code-mancers/dockup/blob/master/apps/dockup/lib/dockup/shell_command.ex#L11-L15) ) . We need to make sure this is being used in all places that require a particular directory to be changed into for running.

**Comment by emilsoman** [comment]
One more todo item is : 
The `run/2` version should call `run/3` with directory as current working directory.
https://github.com/code-mancers/dockup/blob/master/apps/dockup/lib/dockup/shell_command.ex#L4-L9

**Comment by emilsoman** [comment]
@iffyuva are you working on this ?

**Comment by iffyuva** [comment]
nope :|

**Comment by emilsoman** [comment]
Checked Dockup app to see if we're using dir where needed. We're covered, closing the issue.
