### ISSUE TITLE
Store container ids, exposed ports and nginx proxy URLs associated with deployments in the DB

### ISSUE THREAD

**Issue by emilsoman** [code-mancers/dockup#72]
Persist the following:

For each container created as part of the deployment, 
1. Docker container id
2. exposed ports on each container
3. Haikunated URL for each exposed port

**Comment by nithinbekal** [comment]
@emilsoman Parts 2 and 3 are covered in pull request #84. How can we access the docker container id?

**Comment by emilsoman** [comment]
We don't need to do this now. Container IDs can be fetched dynamically using `Dockup.Container.container_ids(project_id)`
